### ISSUE TITLE
Link in readme is dead

### ISSUE THREAD

**Issue by koenr** [moodlehq/moodle-local_amos#4]
The tracker link in readme.md is dead: http://tracker.moodle.org/browse/MDLSITE/component/10653
Please update.
Kind regards
Koen

**Comment by mudrd8mz** [comment]
Thanks Koen. We lost the ability to have these nice URLs to components in some JIRA upgrade. There is no good alternative these days other than URLs like <https://tracker.moodle.org/issues/?jql=project%20%3D%20MDLSITE%20AND%20component%20%3D%20lang.moodle.org%20ORDER%20BY%20created%20DESC>

So I put that one as a link into the README.

**Comment by koenr** [comment]
👍

2018-05-03 22:50 GMT+02:00 David Mudrák <notifications@github.com>:
